name: Blueinput Build

on:
  push:
  pull_request:

jobs:

  windows:
    name: Windows Build (.exe)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Blueinput-windows
        path: build/Release/


  mac:
    name: macOS Build (.app + .dmg)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Create .app bundle
      run: |
        mkdir -p Blueinput.app/Contents/MacOS
        cp build/Blueinput Blueinput.app/Contents/MacOS/

    - name: Create DMG
      run: |
        hdiutil create Blueinput.dmg -srcfolder Blueinput.app -ov

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Blueinput-mac
        path: Blueinput.dmg
